# Generated by Django 4.1.7 on 2023-05-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveragent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='patientnextofkeen',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='redemption',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='loyalty_program',
        ),
        migrations.CreateModel(
            name='PatientProgramEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.patient')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='awards.loyaltyprogram')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
