# Generated by Django 4.1.7 on 2023-04-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_deliverymode_options_alter_hivclinic_options_and_more'),
        ('users', '0002_profile_address_profile_user_type_patient_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveragent',
            name='work_clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.hivclinic'),
            preserve_default=False,
        ),
    ]
