# Generated by Django 4.1.7 on 2023-05-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
        ('users', '0002_alter_deliveragent_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientprogramenrollment',
            unique_together={('patient', 'program')},
        ),
    ]
