# Generated by Django 4.1.7 on 2023-05-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_patientprogramenrollment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redemption',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='redemption',
            name='reward',
        ),
        migrations.DeleteModel(
            name='PatientProgramEnrollment',
        ),
        migrations.DeleteModel(
            name='Redemption',
        ),
    ]
