# Generated by Django 4.1.7 on 2023-04-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_deliveragent_work_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
