# Generated by Django 4.1.7 on 2023-04-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_doctor_doctor_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveragent',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
