# Generated by Django 4.1.7 on 2023-04-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_deliverymode_options_alter_hivclinic_options_and_more'),
        ('users', '0005_deliveragent_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='base_clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hivclinic'),
        ),
    ]
