# Generated by Django 4.1.7 on 2023-04-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_patient_base_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('agent', 'agent'), ('patient', 'patient'), ('doctor', 'doctor')], default='patient', max_length=20),
        ),
    ]
