# Generated by Django 4.1.7 on 2023-04-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_deliverymode_options_alter_hivclinic_options_and_more'),
        ('users', '0008_alter_deliveragent_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hiv_clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hivclinic'),
        ),
    ]
