# Generated by Django 4.1.7 on 2023-05-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_patientprogramenrollment_unique_together'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for requesting facility Transfer')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_approvals', to='users.doctor')),
                ('hospital', models.ForeignKey(help_text='Hospital requesting to transfer to', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='core.hivclinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='users.patient')),
            ],
        ),
    ]
