# Generated by Django 4.1.7 on 2023-05-13 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitytransferrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_approvals', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='facilitytransferrequest',
            name='hospital',
            field=models.ForeignKey(help_text='Hospital requesting to transfer to', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='core.healthfacility'),
        ),
        migrations.AddField(
            model_name='facilitytransferrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='patients.patient'),
        ),
    ]
