# Generated by Django 4.1.7 on 2023-05-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transferrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferrequest',
            options={'ordering': ['-created_at']},
        ),
    ]
