# Generated by Django 4.1.7 on 2023-05-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refillscheme',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
