# Generated by Django 4.1.7 on 2023-05-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deliverytimeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefillScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=50)),
                ('time', models.PositiveIntegerField()),
                ('units', models.CharField(choices=[('days', 'days'), ('months', 'months'), ('weeks', 'weeks')], default='months', max_length=20)),
            ],
        ),
    ]
