# Generated by Django 4.1.7 on 2023-05-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_maritalstatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='maritalstatus',
            name='remote_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
