# Generated by Django 4.1.7 on 2023-05-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_refillscheme_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refillscheme',
            name='units',
            field=models.CharField(choices=[('days', 'days'), ('weeks', 'weeks')], default='days', max_length=20),
        ),
    ]
