# Generated by Django 4.1.7 on 2023-05-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_maritalstatus_remote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitytype',
            name='remote_id',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
