# Generated by Django 4.1.7 on 2023-05-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
