# Generated by Django 4.1.7 on 2023-05-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientnextofkeen',
            name='remote_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
