# Generated by Django 4.1.7 on 2023-05-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_triad_heart_rate_triad_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='national_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
