# Generated by Django 4.1.7 on 2023-04-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='national_id',
            field=models.PositiveIntegerField(default=7654),
            preserve_default=False,
        ),
    ]
