# Generated by Django 4.1.7 on 2023-05-14 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_deliverytimeslot'),
        ('core', '0002_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_of_depletion',
        ),
        migrations.RemoveField(
            model_name='order',
            name='national_id',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.deliverymode'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='agents.deliverytimeslot'),
        ),
    ]
