# Generated by Django 4.1.7 on 2023-05-14 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deliverytimeslot'),
        ('orders', '0002_remove_order_date_of_depletion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.deliverytimeslot'),
        ),
    ]
