# Generated by Django 4.1.7 on 2023-04-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryfeedback',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
