# Generated by Django 4.1.7 on 2023-05-15 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
        ('orders', '0003_alter_order_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medication.appointment'),
        ),
    ]
