# Generated by Django 4.1.7 on 2023-04-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_deliveragent_created_at_and_more'),
        ('orders', '0004_alter_delivery_delivery_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='users.deliveragent'),
            preserve_default=False,
        ),
    ]
