# Generated by Django 4.1.7 on 2023-05-15 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
        ('orders', '0005_remove_delivery_delivery_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='prescription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='medication.artregimen'),
            preserve_default=False,
        ),
    ]
