# Generated by Django 4.1.7 on 2023-04-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_depletion',
            field=models.DateField(),
        ),
    ]
