# Generated by Django 4.1.7 on 2023-04-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_date_of_depletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_medicine',
            field=models.TextField(blank=True, null=True),
        ),
    ]
