# Generated by Django 4.1.7 on 2023-04-29 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_delivery_delivery_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='orders.delivery')),
            ],
        ),
    ]
