# Generated by Django 4.1.7 on 2023-04-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_agenttrip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenttrip',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='deliveryfeedback',
            name='points_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
