# Generated by Django 4.1.7 on 2023-04-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Indicator if it can be assign to new patients by default'),
        ),
    ]
