# Generated by Django 4.1.7 on 2023-05-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
