# Generated by Django 4.1.7 on 2023-04-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_loyaltyprogram_created_at_reward_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loyaltyprogram',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/awards/programs'),
        ),
        migrations.AddField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/awards/rewards'),
        ),
    ]
