# Generated by Django 4.1.7 on 2023-05-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_alter_reward_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='entry_points',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
