# Generated by Django 4.1.7 on 2023-04-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_alter_loyaltyprogram_options_alter_reward_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='name',
            field=models.CharField(default='default name', help_text='Name of the program reward', max_length=255),
            preserve_default=False,
        ),
    ]
